# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'h0h0' do
   pod 'JTSImageViewController'
   pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
   pod 'React', :path => '../node_modules/react-native'
   pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
   pod 'lottie-ios', :path => '../node_modules/lottie-ios'
   pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

end
